apiVersion: apps/v1
kind: Deployment
metadata:
  name: loanrisk
  namespace: ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loanrisk
  template:
    metadata:
      labels:
        app: loanrisk
    spec:
      containers:
      - name: loanrisk
        image: ${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: loanrisk-service
  namespace: ml
spec:
  selector:
    app: loanrisk
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
