apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: loanrisk-model
  namespace: seldon
spec:
  name: loanrisk-deployment
  predictors:
    - name: default
      replicas: 1
      graph:
        name: loanrisk
        implementation: CUSTOM
        modelUri: "dummy"
        endpoint:
          type: REST
        type: MODEL
      componentSpecs:
        - spec:
            containers:
              - name: loanrisk
                image: ${IMAGE_TAG}
                imagePullPolicy: Always
                ports:
                  - containerPort: 3000
