apiVersion: apps/v1
kind: Deployment
metadata:
  name: loanrisk
  namespace: seldon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loanrisk
  template:
    metadata:
      labels:
        app: loanrisk
    spec:
      containers:
      - name: loanrisk
        image: jy323/loanriskservice:v2
        ports:
        - containerPort: 3000
