newdata_folder: data/raw/new               # Folder containing new raw loan data files (if any)
base_train_path: data/processed/train_loan.csv
remove_duplicates: true
positive_loanstatus:
  - "Paid Off Loan"
negative_loanstatus:
  - "External Collection"
  - "Internal Collection"
  - "Settlement Paid Off"
  - "Settled Bankruptcy"
  - "Charged Off"
  - "Charged Off Paid Off"
  - "Settlement Pending Paid Off"

drop_columns:
  - loanId
  - anon_ssn
  - approved
  - originated
  - originatedDate
  - applicationDate
  - isFunded
  - fpStatus
  - clarityFraudId
