remove_duplicates: true
newdata_folder: "data/raw/new"

# base train dataset
base_train_path: "data/processed/train_loan.csv" 

drop_columns:
  - loanId
  - anon_ssn
  - clarityFraudId
  - originated
  - originatedDate
  - isFunded
  - fpStatus
  - approved
  - applicationDate

# target variable
positive_loanstatus:
- "Paid Off Loan"

negative_loanstatus:
- "External Collection"
- "Internal Colelction"
- "Returned Item"
- "Settlement Paid Off"
- "Settled Bankruptcy"
- "Charged Off"
- "Charged Off Paid Off"


