original_data_folder: data/raw/original        # Path to original raw loan data file(s)
remove_duplicates: true
positive_loanstatus:
  - "Paid Off Loan"
negative_loanstatus:
  - "External Collection"
  - "Internal Collection"
  - "Settlement Paid Off"
  - "Settled Bankruptcy"
  - "Charged Off"
  - "Charged Off Paid Off"
  - "Settlement Pending Paid Off"

drop_columns:
  - loanId
  - anon_ssn
  - approved
  - originated
  - originatedDate
  - applicationDate
  - isFunded
  - fpStatus
  - clarityFraudId


test_ratio: 0.2               # Proportion of data to use as test set
random_state: 42             # Random seed for reproducibility
balance_mode: "smote"         # Options: "none", "undersample", "oversample", "smote"
