dataset_path: data/processed/loan_clean_latest.csv
target_col: risk_indicator
test_size: 0.3
random_state: 42

# LightGBM hyperparameters (default training)
learning_rate: 0.05
num_leaves: 31
num_boost_round: 1000
early_stopping_rounds: 50

# Hyperparameter tuning settings
grid_search: true             # Set true to perform grid search
param_grid:
  learning_rate: [0.01, 0.05, 0.1]
  num_leaves: [15, 31, 63]
grid_cv: 3
grid_verbose: 1
grid_n_jobs: -1
grid_scoring: "roc_auc"

# Model output and MLflow settings
model_dir: output/models
model_prefix: lightgbm_model
grid_model_prefix: lightgbm_best_model
grid_search_results_dir: output/grid_search_results
threshold: 0.5                  # Probability threshold for classifying as positive
tracking_uri: http://127.0.0.1:5000 # Mlflow ui 
experiment_name: LoanRisk
